const sampleListings = [
    {
      title: "Fresh Organic Carrots",
      description: "Locally grown, pesticide-free carrots. Crisp and sweet, perfect for snacking or cooking.",
      image: "https://www.greendna.in/cdn/shop/products/basket-carrots-close-up-37641_1024x1024@2x.jpg?v=1632668896", 
      price: 25, 
      location: "Farmville, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Ripe Juicy Mangoes",
      description: "Sun-ripened Alphonso mangoes, known for their rich flavor and sweetness.",
      image: "https://www.india.com/wp-content/uploads/2022/05/Mango-Eating-Tips.jpg",
      price: 75, 
      location: "Sunny Orchards, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Premium Basmati Rice",
      description: "Aromatic and long-grain Basmati rice, ideal for biryanis and other rice dishes.",
      image: "https://flourworks.in/wp-content/uploads/2023/06/1-12.jpeg",
      price: 60, 
      location: "Green Fields Farm, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Healthy Broccoli Florets",
      description: "Freshly harvested broccoli florets, packed with vitamins and nutrients.",
      image: "https://gourmetgarden.in/cdn/shop/products/Broccoli_-_Florets_25687d49-bed7-413e-85d4-853b5508e3a6_1280x.jpg?v=1741411575",
      price: 35,
      location: "Healthy Harvest Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Sweet and Tangy Oranges",
      description: "Juicy and refreshing oranges, perfect for a healthy snack or juice.",
      image: "https://thumbs.dreamstime.com/b/small-sweet-tangy-mandarin-oranges-popular-citrus-fruit-known-their-easy-to-peel-segments-re-often-enjoyed-as-355324105.jpg",
      price: 40, 
      location: "Citrus Grove, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Whole Wheat Flour",
      description: "Stone-ground whole wheat flour, perfect for baking bread and other goods.",
      image: "https://urbandelight.in/cdn/shop/files/WhatsAppImage2023-12-14at03.34.49.jpg?v=1702553785",
      price: 50, 
      location: "Grain Mill, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Farm-Fresh Eggs",
      description: "Free-range chicken eggs, rich in protein and flavor.",
      image: "https://cdn11.bigcommerce.com/s-25ghynqpgv/images/stencil/1920x1280/uploaded_images/the-benefits-of-having-farm-fresh-eggs-300x180.jpg?t=1649173672",
      price: 10, 
      location: "Happy Hen Farm, Anytown",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Organic Spinach",
      description: "Fresh and leafy spinach, packed with iron and other essential nutrients.",
      image: "https://parajorganics.com/wp-content/uploads/2019/12/spinach.jpg",
      price: 20, 
      location: "Green Leaf Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Red Delicious Apples",
      description: "Crisp and sweet red apples, perfect for snacking or baking.",
      image: "https://www.fruits365.shop/cdn/shop/products/washington1.jpg?v=1636264493",
      price: 55,
      location: "Apple Orchard, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Brown Rice",
      description: "Nutritious and fiber-rich brown rice, a healthy alternative to white rice.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDwM28ppBIe2rD2lLqUpL8KZFEmkZ6R6I2AA&s",
      price: 45, 
      location: "Healthy Grains Farm, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
      {
      title: "Free-Range Chicken",
      description: "Whole, unprocessed free-range chicken, ready for cooking.",
      image: "https://tunleyfarmbutchers.co.uk/wp-content/uploads/2020/11/free_range_whole_chickens_opt.jpg",
      price: 120, 
      location: "Countryside Farm, Anytown",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Freshly Picked Strawberries",
      description: "Juicy and sweet strawberries, perfect for desserts or snacking.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYacc2C-M7preEFL8jsRcd4QgmV-xC5MaAbg&s",
      price: 60, 
      location: "Berry Patch Farm, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Oats",
      description: "Rolled oats, a healthy and versatile grain for breakfast or baking.",
      image: "https://media.post.rvohealth.io/wp-content/uploads/2020/03/oats-oatmeal-732x549-thumbnail.jpg",
      price: 30, 
      location: "Oat Fields, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Lettuce",
      description: "Crisp and fresh lettuce, perfect for salads and sandwiches.",
      image: "https://m.media-amazon.com/images/I/71uoTOXeFEL._AC_UF1000,1000_QL80_.jpg",
      price: 15, 
      location: "Salad Greens Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Bananas",
      description: "Ripe and creamy bananas, a healthy and convenient snack.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfOd-anrcJKgEvB1aFqVM-9p3RCWiEvsapHg&s",
      price: 20, 
      location: "Tropical Farms, Anytown",
      category: "Fruits",
      owner: "Nouman",
    }, {
      title: "Organic Green Beans",
      description: "Freshly picked, crisp green beans.",
      image: "https://5.imimg.com/data5/SELLER/Default/2024/12/472949336/HH/YS/WQ/110424049/fresh-green-beans.jpg",
      price: 30,
      location: "Bean Fields",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Blueberries",
      description: "Sweet and juicy blueberries.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkaRYA3YtnHmmmLs_RfYtReyNjpHdfPZ29Hw&s",
      price: 80,
      location: "Blueberry Hill",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Rye Flour",
      description: "Dark and flavorful rye flour.",
      image: "https://images.hollandandbarrettimages.co.uk/health-hub/2021/m05/rye-flour1-1759453148.jpg",
      price: 65,
      location: "Rye Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Turkey",
      description: "Whole, unprocessed turkey.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGLVZKSkId6YJmpFq_2yx0tT1hyWuBMa5f9g&s",
      price: 150,
      location: "Turkey Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Raspberries",
      description: "Tart and delicious raspberries.",
      image: "https://cdn.britannica.com/83/156583-050-4A1FABB5/Red-raspberries.jpg",
      price: 70,
      location: "Raspberry Patch",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Barley",
      description: "Pearl barley.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYcTR-jIFic8PqyFLnqm21FuueuXLJ5g4_HQ&s",
      price: 40,
      location: "Barley Fields",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Pears",
      description: "Juicy and sweet pears.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdDaLyID9gkZpC9Gulq0VhQDDwH-MkclpvwQ&s",
      price: 50,
      location: "Pear Orchard",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Couscous",
      description: "Fine semolina couscous.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX2BihU1cEN4T0UgWWc9OUV_6vIecTJ_MuZg&s",
      price: 55,
      location: "Couscous Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Goose Eggs",
      description: "Large and rich goose eggs.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHWbfSXX5eQ0gJM4vR_h3lxTXpilezMNTK3w&s",
      price: 20,
      location: "Goose Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Kale",
      description: "Nutritious and leafy kale.",
      image: "https://cdn.britannica.com/74/181374-050-83F7B492/kale-leaves.jpg",
      price: 25,
      location: "Kale Farm",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Plums",
      description: "Sweet and juicy plums.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaaN8sp0hX6gsOUEE-U6mHj0wf_UE40jYEpw&s",
      price: 60,
      location: "Plum Orchard",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Spelt Flour",
      description: "Nutty and slightly sweet spelt flour.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlmqVp6KtcYszCffziGt8_yqmNvoSmbSW9rA&s",
      price: 75,
      location: "Spelt Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Guinea Fowl",
      description: "Lean and flavorful guinea fowl.",
      image: "https://media.istockphoto.com/id/465391723/photo/guinea-fowl.jpg?s=612x612&w=0&k=20&c=6H4usa5BOTF95DrjWrrRezFCzx1PTtCzWnnkjySUEBY=",
      price: 100,
      location: "Guinea Fowl Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Radishes",
      description: "Crisp and peppery radishes.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5oiqNqADfh9hm7pkJ0oOy1bzvvBR3Eg05ig&s",
      price: 15,
      location: "Radish Farm",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Cherries",
      description: "Sweet and tart cherries.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToqflTv6wCsGxHVhVMGs3GQ8xhit3Gzd2y1A&s",
      price: 90,
      location: "Cherry Orchard",
      category: "Fruits",
      owner: "Nouman",
    },

];

module.exports = { data: sampleListings };